### ISSUE TITLE
Small Tips

### ISSUE THREAD

**Issue by ArchBlood** [StevenJoynt/HumHub-RSS-Reader#14]
Looking through your `MarkdownHelper.php` I see that you're using `MarkdownHelper::`, it is better to just use `self::` if you're using the class from the same file, I would also like to note that you aren't required to use `$` statement to request `$article`, `$level` and etc. just use `self::article`, `self::level` and etc.

**Comment by StevenJoynt** [comment]
Thanks for that. I'm really grateful as I've been working alone for a while, so nobody gives me feedback on the quality of my coding.
I've fixed the issues you suggested and also renamed some variables to make them more meaningful.
Committed 644b834ac44f50ff4e6395e7e6b00125e2b6ba62
