### ISSUE TITLE
Class CActiveForm is removed in HumHub 1.11.*

### ISSUE THREAD

**Issue by ralfblask** [StevenJoynt/HumHub-RSS-Reader#21]
I get an error when I try to configure the rss module in a space.

The app.log says:
  Class 'humhub\compat\CActiveForm' not found in /html/humhub/protected/modules/rss/views/rss/config.php:12

The changelog of humhubn/humhub says:
  Enh #4823: Removed CHTML and CActiveForm classes as well as usages (plus refactoring)

@StevenJoynt

**Comment by StevenJoynt** [comment]
Thanks @ArchBlood - works like a dream
It would have been a few days before I could have found the time to even investigate what to change.
Thank you for your quick and accurate response.

**Comment by Vjnm** [comment]
Hello everyone;
RSS was working perfectly until the upgrade. Now I get this message:
Class 'humhub\compat\CActiveForm' not found

It seems the problem is solve just by reading the above comments but I don't know how to proceed. Any help is very much appreciated.
Thanks in advance.
Vin

**Comment by ArchBlood** [comment]
> Hello everyone;
> RSS was working perfectly until the upgrade. Now I get this message:
> Class 'humhub\compat\CActiveForm' not found
> 
> It seems the problem is solve just by reading the above comments but I don't know how to proceed. Any help is very much appreciated.
> Thanks in advance.
> Vin
> 

Did you download a new version of the module then upload it and overwrite the old version?

If you did then clear your site cache and check again

**Comment by Vjnm** [comment]
Thanks for answering so quickly. I followed your procedure. The error is gone and I was able to activate and enter the RSS URL. 
Thank you.
Vin
