### ISSUE TITLE
Config option to include image (if available)

### ISSUE THREAD

**Issue by StevenJoynt** [StevenJoynt/HumHub-RSS-Reader#3]
Provide a config option to say if each RSS item should display its associated image.
And if so, specify the maximum width of the image. Default to 200px.

**Comment by samuk** [comment]
This would be great! The module seems to be working well for me so far, images would be really nice

**Comment by StevenJoynt** [comment]
Pictures are now being displayed correctly.
The configuration of the module allows for pictures to be turned on/off and a maximum size can be specified.
